version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: obsidiandb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${RAG_DBUSER:-dbuser}
      POSTGRES_PASSWORD: ${RAG_DBPASSWORD:-dbuser}
      POSTGRES_DB: ${RAG_DBNAME:-obsidiandb}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
