#!/usr/bin/env python
# coding:utf-8

"""
ESSENTIAL PROCESS:
Scaffolds a new Bastien-Antigravity microservice adhering to canonical repository
structure, mandatory root files, Docker standards, and BDD specifications.

DATA FLOW:
1. Input: Service name, target language (Go/Python/Rust), port, description.
2. Logic: Generates folder architecture, creates the 9 mandatory root files,
   establishes standalone.yaml symlink, and generates BDD specs in 02-Business-BDD.
3. Output: Production-ready microservice directory and ecosystem registration snippets.

KEY PARAMETERS:
- --name: Name of the microservice (kebab-case, e.g., market-observer).
- --lang: Target language ('go', 'python', 'rust'). Defaults to 'go'.
- --port: Primary service port (e.g., 8090).
- --dest: Target directory path (defaults to workspace root / <name>).
- --dry-run: Preview file fabrication without writing to disk.
"""

import argparse
import os
import sys
from pathlib import Path

# -----------------------------------------------------------------------------

def resolve_workspace_root() -> Path:
    """Resolves the Bastien-Antigravity workspace root dynamically."""
    current = Path(__file__).resolve()
    for parent in [current] + list(current.parents):
        if (parent / "docker-deployment").exists() and (parent / "microservice-toolbox").exists():
            return parent
    return Path.cwd()

# -----------------------------------------------------------------------------

def create_file(path: Path, content: str, dry_run: bool = False) -> None:
    """Creates a file with parent directory creation, respecting dry-run mode."""
    if dry_run:
        print(f"  [DRY-RUN] Would create file: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  ✅ Created: {path}")

# -----------------------------------------------------------------------------

def create_symlink(target_path: Path, link_target: str, dry_run: bool = False) -> None:
    """Creates a symbolic link, respecting dry-run mode."""
    if dry_run:
        print(f"  [DRY-RUN] Would symlink: {target_path} -> {link_target}")
        return
    target_path.parent.mkdir(parents=True, exist_ok=True)
    if target_path.is_symlink() or target_path.exists():
        target_path.unlink()
    os.symlink(link_target, target_path)
    print(f"  🔗 Symlinked: {target_path} -> {link_target}")

# -----------------------------------------------------------------------------

def generate_go_scaffold(target_dir: Path, name: str, port: int, desc: str, dry_run: bool) -> None:
    """Generates the Go microservice skeleton and source files."""
    cap_name = name.replace("-", "_")

    # 1. cmd/<name>/main.go
    main_go = f"""package main

// =============================================================================
// [STARTER TEMPLATE / EXAMPLE ENTRYPOINT]
// NOTE: This is a scaffolded Go service entrypoint generated by scaffold_microservice.py.
// Developers & AI Agents: Extend or replace this file with your actual service logic.
//
// ESSENTIAL PROCESS:
// Boots and initializes the {name} microservice, establishing
// dynamic capabilities discovery and lifecycle management.
//
// DATA FLOW:
// 1. Input: Loads configuration using the layered microservice-toolbox loader.
// 2. Logic: Starts core service controllers and listens on canonical capability ports.
// 3. Output: Runs service workers under graceful lifecycle supervision.
//
// KEY PARAMETERS:
// - {cap_name}: Capabilities section defining service network ports and parameters.
// =============================================================================

import (
	"context"
	"os"

	"{name}/src/core"
	toolbox_bootstrap "github.com/Bastien-Antigravity/microservice-toolbox/go/pkg/bootstrap"
	toolbox_lifecycle "github.com/Bastien-Antigravity/microservice-toolbox/go/pkg/lifecycle"
)

// -----------------------------------------------------------------------------

func main() {{
	// 1. Initialize Service via Unified Ecosystem Bootstrapper
	appConfig, appLogger := toolbox_bootstrap.BootstrapService("{name}")
	defer appLogger.Close()

	appLogger.Info("Starting {name} under profile: %s", appConfig.Profile)

	// 2. Resolve Service Listen Address
	addr, err := appConfig.GetListenAddr("{cap_name}")
	if err != nil || addr == "" {{
		addr = "127.0.0.1:{port}"
		appLogger.Warning("Falling back to default listen address %s: %v", addr, err)
	}}

	// 3. Instantiate Core Controller
	ctrl := core.NewController(appConfig, appLogger)

	// 4. Initialize Lifecycle Manager
	lm := toolbox_lifecycle.NewManagerWithLogger(appLogger)

	lm.Register("StopService", func() error {{
		appLogger.Info("Stopping {name} worker...")
		return ctrl.Stop(context.Background())
	}})

	// 5. Start Service Worker Loop
	go func() {{
		if err := ctrl.Start(addr); err != nil {{
			appLogger.Critical("Service worker failed: %v", err)
			os.Exit(1)
		}}
	}}()

	// 6. Await OS Signals for Graceful Termination
	lm.Wait(context.Background())
}}
"""
    create_file(target_dir / f"cmd/{name}/main.go", main_go, dry_run)

    # 2. src/core/controller.go
    controller_go = f"""package core

// =============================================================================
// [STARTER TEMPLATE / DUMMY WORKER CONTROLLER]
// NOTE: This is a dummy example controller demonstrating clean lifecycle management.
// Developers & AI Agents: Replace this starter implementation with your domain logic.
//
// ESSENTIAL PROCESS:
// Central business logic controller for {name}.
//
// DATA FLOW:
// 1. Input: Requests, events, and configuration states.
// 2. Logic: Executes domain transformations and coordinates components.
// 3. Output: Telemetry, event publishes, and structured logs.
//
// KEY PARAMETERS:
// - None
// =============================================================================

import (
	"context"

	toolbox_config "github.com/Bastien-Antigravity/microservice-toolbox/go/pkg/config"
	unilog_interfaces "github.com/Bastien-Antigravity/universal-logger/src/interfaces"
)

// -----------------------------------------------------------------------------

// Controller manages the lifecycle and operations of {name}.
type Controller struct {{
	appConfig *toolbox_config.AppConfig
	logger    unilog_interfaces.Logger
}}

// -----------------------------------------------------------------------------

// NewController instantiates a new {name} Controller.
func NewController(appConfig *toolbox_config.AppConfig, logger unilog_interfaces.Logger) *Controller {{
	return &Controller{{
		appConfig: appConfig,
		logger:    logger,
	}}
}}

// -----------------------------------------------------------------------------

// Start initializes internal workers and listens on the given address.
func (c *Controller) Start(addr string) error {{
	c.logger.Info("{name} controller running on %s", addr)
	return nil
}}

// -----------------------------------------------------------------------------

// Stop terminates active workers gracefully.
func (c *Controller) Stop(ctx context.Context) error {{
	c.logger.Info("{name} controller shutdown complete")
	return nil
}}
"""
    create_file(target_dir / "src/core/controller.go", controller_go, dry_run)

    # 3. src/interfaces/interfaces.go
    interfaces_go = f"""package interfaces

// =============================================================================
// [STARTER TEMPLATE / DUMMY INTERFACE CONTRACT]
// NOTE: This is an example interface contract demonstrating decoupling.
// Developers & AI Agents: Replace with your service interfaces.
//
// ESSENTIAL PROCESS:
// Defines domain interfaces for {name} to maintain strict decoupling.
//
// DATA FLOW:
// Contract definitions consumed by concrete providers.
// =============================================================================

import "context"

// -----------------------------------------------------------------------------

// Service defines the contract for {name} operations.
type Service interface {{
	Execute(ctx context.Context) error
}}
"""
    create_file(target_dir / "src/interfaces/interfaces.go", interfaces_go, dry_run)

    # 4. src/models/models.go
    models_go = f"""package models

// =============================================================================
// [STARTER TEMPLATE / DUMMY MODEL SCHEMA]
// NOTE: This is an example data model schema.
// Developers & AI Agents: Replace or extend this with your domain models.
//
// ESSENTIAL PROCESS:
// Data structures and schemas for {name}.
// =============================================================================

// StatusPayload represents the operational health telemetry of {name}.
type StatusPayload struct {{
	ServiceName string `json:"service_name"`
	Status      string `json:"status"`
	Timestamp   int64  `json:"timestamp"`
}}
"""
    create_file(target_dir / "src/models/models.go", models_go, dry_run)

    # 5. go.mod
    go_mod = f"""module github.com/Bastien-Antigravity/{name}

go 1.25

require (
	github.com/Bastien-Antigravity/distributed-config v0.0.0
	github.com/Bastien-Antigravity/flexible-logger v0.0.0
	github.com/Bastien-Antigravity/microservice-toolbox v0.0.0
	github.com/Bastien-Antigravity/safe-socket v0.0.0
	github.com/Bastien-Antigravity/universal-logger v0.0.0
)

replace (
	github.com/Bastien-Antigravity/distributed-config => ../distributed-config
	github.com/Bastien-Antigravity/flexible-logger => ../flexible-logger
	github.com/Bastien-Antigravity/microservice-toolbox => ../microservice-toolbox
	github.com/Bastien-Antigravity/safe-socket => ../safe-socket
	github.com/Bastien-Antigravity/universal-logger => ../universal-logger
)
"""
    create_file(target_dir / "go.mod", go_mod, dry_run)

    # 6. .golangci.yml
    golangci_yml = """version: "2"
run:
  timeout: 5m

linters:
  enable:
    - staticcheck
    - govet
    - ineffassign
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "QF1008"
"""
    create_file(target_dir / ".golangci.yml", golangci_yml, dry_run)

    # 7. src/core/controller_test.go
    controller_test_go = f"""package core

import (
	"context"
	"testing"

	toolbox_config "github.com/Bastien-Antigravity/microservice-toolbox/go/pkg/config"
	unilog_interfaces "github.com/Bastien-Antigravity/universal-logger/src/interfaces"
)

// mockLogger embeds unilog_interfaces.Logger to ensure decoupling and interface compatibility.
type mockLogger struct {{
	unilog_interfaces.Logger
}}

func (m *mockLogger) Info(format string, args ...interface{{}})     {{}}
func (m *mockLogger) Warning(format string, args ...interface{{}})  {{}}
func (m *mockLogger) Error(format string, args ...interface{{}})    {{}}
func (m *mockLogger) Critical(format string, args ...interface{{}}) {{}}
func (m *mockLogger) Debug(format string, args ...interface{{}})    {{}}
func (m *mockLogger) Close() error                                {{ return nil }}

func TestController_Lifecycle(t *testing.T) {{
	cfg := &toolbox_config.AppConfig{{Profile: "test"}}
	logger := &mockLogger{{}}

	ctrl := NewController(cfg, logger)
	if ctrl == nil {{
		t.Fatal("expected NewController to return non-nil instance")
	}}

	if err := ctrl.Start("127.0.0.1:{port}"); err != nil {{
		t.Fatalf("unexpected Start error: %v", err)
	}}

	if err := ctrl.Stop(context.Background()); err != nil {{
		t.Fatalf("unexpected Stop error: %v", err)
	}}
}}
"""
    create_file(target_dir / "src/core/controller_test.go", controller_test_go, dry_run)

# -----------------------------------------------------------------------------

def generate_rust_scaffold(target_dir: Path, name: str, port: int, desc: str, dry_run: bool) -> None:
    """Generates the Rust microservice skeleton and source files."""
    cap_name = name.replace("-", "_")

    # 1. Cargo.toml
    cargo_toml = f"""[package]
name = "{name}"
version = "0.0.1"
edition = "2021"
description = "{desc}"

[dependencies]
tokio = {{ version = "1.38", features = ["full"] }}
serde = {{ version = "1.0", features = ["derive"] }}
serde_json = "1.0"

[dev-dependencies]
tokio-test = "0.4"
"""
    create_file(target_dir / "Cargo.toml", cargo_toml, dry_run)

    # 2. src/main.rs
    main_rs = f"""// =============================================================================
// [STARTER TEMPLATE / EXAMPLE ENTRYPOINT]
// NOTE: This is a scaffolded Rust service entrypoint generated by scaffold_microservice.py.
// Developers & AI Agents: Extend or replace this file with your actual service logic.
//
// ESSENTIAL PROCESS:
// Boots and initializes the {name} microservice with Tokio runtime.
//
// DATA FLOW:
// 1. Input: Loads configuration from standalone profile.
// 2. Logic: Starts core service controller.
// 3. Output: Runs service workers under graceful Tokio lifecycle supervision.
//
// KEY PARAMETERS:
// - {cap_name}: Capability section defining service network ports.
// =============================================================================

mod core;

// -----------------------------------------------------------------------------

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {{
    println!("Starting {name} (version 0.0.1)...");

    let ctrl = core::Controller::new("{name}");
    ctrl.start("127.0.0.1:{port}").await?;

    // Await termination signal
    tokio::signal::ctrl_c().await?;
    println!("Termination signal received, shutting down {name}...");

    ctrl.stop().await?;
    Ok(())
}}
"""
    create_file(target_dir / "src/main.rs", main_rs, dry_run)

    # 3. src/core/mod.rs
    core_rs = f"""// =============================================================================
// [STARTER TEMPLATE / DUMMY WORKER CONTROLLER]
// NOTE: This is an example controller demonstrating clean async worker management.
//
// ESSENTIAL PROCESS:
// Central business logic controller for {name}.
//
// DATA FLOW:
// Coordinates background tasks and handles health checks.
//
// KEY PARAMETERS:
// - None
// =============================================================================

pub struct Controller {{
    pub name: String,
}}

// -----------------------------------------------------------------------------

impl Controller {{
    pub fn new(name: &str) -> Self {{
        Self {{
            name: name.to_string(),
        }}
    }}

    pub async fn start(&self, addr: &str) -> Result<(), Box<dyn std::error::Error>> {{
        println!("{{}} controller running on {{}}", self.name, addr);
        Ok(())
    }}

    pub async fn stop(&self) -> Result<(), Box<dyn std::error::Error>> {{
        println!("{{}} controller shutdown complete", self.name);
        Ok(())
    }}
}}
"""
    create_file(target_dir / "src/core/mod.rs", core_rs, dry_run)

    # 4. tests/test_basic.rs
    test_rs = f"""// =============================================================================
// [STARTER TEMPLATE / DUMMY TEST SUITE]
// NOTE: Starter integration test for {name}.
// =============================================================================

#[tokio::test]
async fn test_scaffold_initialization() {{
    assert!(true);
}}
"""
    create_file(target_dir / "tests/test_basic.rs", test_rs, dry_run)

# -----------------------------------------------------------------------------

def generate_python_scaffold(target_dir: Path, name: str, port: int, desc: str, dry_run: bool) -> None:
    """Generates the Python microservice skeleton and architecture folders."""
    cap_name = name.replace("-", "_")

    # 1. main.py
    main_py = f"""#!/usr/bin/env python
# coding:utf-8

\"\"\"
================================================================================
[STARTER TEMPLATE / EXAMPLE ENTRYPOINT]
NOTE: This is a scaffolded entrypoint example generated by scaffold_microservice.py.
Developers & AI Agents: Replace or extend this file with your actual business logic,
event subscribers, background workers, or API endpoints.
================================================================================

ESSENTIAL PROCESS:
Entry point for the {name} microservice.

DATA FLOW:
1. Input: Loads configuration via microservice-toolbox.
2. Logic: Boots controller and connects to ecosystem capabilities.
3. Output: Telemetry, event publishing, and logs.

KEY PARAMETERS:
- {cap_name}: Primary capability configuration.
\"\"\"

import sys
from pathlib import Path

# Bootstrap configuration and logger via microservice-toolbox
from microservice_toolbox.config.loader import load_config
from microservice_toolbox.logger import UniLog
from src.core.controller import Controller

def main():
    # Load layered configuration (CLI > local YAML > native.yaml > ENV)
    config = load_config("standalone")
    logger = UniLog(app_name="{name}", config_profile="standalone")
    logger.info("Starting {name} (starter template)...")

    # Instantiate and start the example worker controller
    controller = Controller(config=config, logger=logger)
    controller.start()

if __name__ == "__main__":
    main()
"""
    create_file(target_dir / "main.py", main_py, dry_run)

    # 2. src/core/controller.py
    controller_py = f"""#!/usr/bin/env python
# coding:utf-8

\"\"\"
================================================================================
[STARTER TEMPLATE / DUMMY WORKER CONTROLLER]
NOTE: This is a dummy example controller demonstrating the Bastien-Antigravity
Python Integration Specialist coding standards:
  1. One-Class Rule: Exactly one primary class per file.
  2. Keyword-Only Arguments (*): Enforces explicit named arguments for safety.
  3. Standard Constructor: Injects 'config' and 'logger', defaults Name.
Developers & AI Agents: Replace this dummy worker controller with your domain-specific
business processing, background loops, or message handlers.
================================================================================

ESSENTIAL PROCESS:
Central domain controller managing workers and lifecycle for {name}.

DATA FLOW:
1. Input: Configuration and logger injected via constructor.
2. Logic: Coordinates background tasks and handles health checks.
3. Output: Telemetry events and operational logs.

KEY PARAMETERS:
- config: Ecosystem configuration provider.
- logger: Unified logger instance.
\"\"\"

from typing import Any, Optional

class Controller:
    \"\"\"
    Example dummy controller managing lifecycle and operations of {name}.
    Replace this with your actual microservice controller implementation.
    \"\"\"

    def __init__(self, *, config: Any, logger: Any, name: Optional[str] = None):
        self.config = config
        self.logger = logger
        self.Name = name or self.__class__.__name__

    def start(self) -> None:
        # Example starter logic - replace with actual background workers
        self.logger.info(f"{{self.Name}} : [DUMMY] Controller started successfully.")

    def stop(self) -> None:
        # Example cleanup logic - replace with actual worker teardown
        self.logger.info(f"{{self.Name}} : [DUMMY] Controller terminated gracefully.")
"""
    create_file(target_dir / "src/core/controller.py", controller_py, dry_run)

    # 3. src/interfaces/service.py
    service_py = f"""#!/usr/bin/env python
# coding:utf-8

\"\"\"
================================================================================
[STARTER TEMPLATE / DUMMY PROTOCOL CONTRACT]
NOTE: This is a dummy example interface protocol demonstrating type decoupling.
Developers & AI Agents: Define your service-specific protocols, contracts, and
abstract base classes here to keep domain logic decoupled from external I/O.
================================================================================

ESSENTIAL PROCESS:
Contract definitions and protocols for {name}.

DATA FLOW:
Protocol definitions consumed by concrete provider implementations.

KEY PARAMETERS:
- ServiceProtocol: Example base operational protocol.
\"\"\"

from typing import Protocol, runtime_checkable

@runtime_checkable
class ServiceProtocol(Protocol):
    \"\"\"Example protocol contract. Replace with domain operations.\"\"\"
    def execute(self) -> bool:
        ...
"""
    create_file(target_dir / "src/interfaces/service.py", service_py, dry_run)

    # 4. src/models/status.py
    status_py = f"""#!/usr/bin/env python
# coding:utf-8

\"\"\"
================================================================================
[STARTER TEMPLATE / DUMMY DATA MODEL]
NOTE: This is a dummy example data model demonstrating:
  1. Dataclass usage for typed payload structures.
  2. Language-idiomatic naming standard for domain models (e.g. StatusPayload).
Developers & AI Agents: Replace or extend this file with your actual service schemas,
telemetry models, and request/response payloads.
================================================================================

ESSENTIAL PROCESS:
Data models and schemas for {name}.

DATA FLOW:
Structured payload models for status reporting and health telemetry.

KEY PARAMETERS:
- StatusPayload: Example health telemetry dataclass.
\"\"\"

from dataclasses import dataclass
import time

@dataclass
class StatusPayload:
    \"\"\"Example dummy status payload model.\"\"\"
    service_name: str
    status: str
    timestamp: float = time.time()
"""
    create_file(target_dir / "src/models/status.py", status_py, dry_run)

    # 5. requirements.txt
    reqs_txt = """microservice-toolbox
universal-logger
pytest
"""
    create_file(target_dir / "requirements.txt", reqs_txt, dry_run)

    # 6. tests/test_basic.py
    test_py = f"""# =============================================================================
# [STARTER TEMPLATE / DUMMY TEST SUITE]
# NOTE: This is a dummy test suite to verify pytest test runner integration.
# Developers & AI Agents: Replace these placeholder assertions with rigorous unit
# and integration tests for {name}.
# =============================================================================

def test_scaffold_initialization():
    \"\"\"Verify that basic pytest execution passes in the scaffolded environment.\"\"\"
    assert True
"""
    create_file(target_dir / "tests/test_basic.py", test_py, dry_run)

# -----------------------------------------------------------------------------

def generate_common_files(target_dir: Path, name: str, lang: str, port: int, desc: str, dry_run: bool) -> None:
    """Generates files mandatory across all languages: Dockerfile, compose, AGENTS.md, etc."""
    cap_name = name.replace("-", "_")

    # 1. Dockerfile (Multi-stage compliant with 12-Docker-Deployment-Standards.md)
    if lang == "go":
        dockerfile = f"""# === BUILD STAGE ===
FROM golang:1.25-alpine AS builder

LABEL org.opencontainers.image.source="https://github.com/Bastien-Antigravity/{name}"

RUN apk add --no-cache git gcc musl-dev ca-certificates tzdata

WORKDIR /workspace

# Clone shared library modules for replace directives in builder stage
RUN git clone --depth 1 -b develop https://github.com/Bastien-Antigravity/microservice-toolbox.git /workspace/microservice-toolbox && \\
    git clone --depth 1 -b develop https://github.com/Bastien-Antigravity/distributed-config.git /workspace/distributed-config && \\
    git clone --depth 1 -b develop https://github.com/Bastien-Antigravity/safe-socket.git /workspace/safe-socket && \\
    git clone --depth 1 -b develop https://github.com/Bastien-Antigravity/universal-logger.git /workspace/universal-logger && \\
    git clone --depth 1 -b develop https://github.com/Bastien-Antigravity/flexible-logger.git /workspace/flexible-logger

# Copy service source
WORKDIR /workspace/{name}
COPY . .

# Ensure dependencies are tidy and build binary
RUN go mod tidy && \\
    CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /{name}-bin ./cmd/{name}

# === RUNTIME STAGE ===
FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /{name}

COPY --from=builder /{name}-bin /{name}/{name}

ENTRYPOINT ["/{name}/{name}"]
"""
    elif lang == "rust":
        dockerfile = f"""# === BUILD STAGE ===
FROM rust:1.80-alpine AS builder

LABEL org.opencontainers.image.source="https://github.com/Bastien-Antigravity/{name}"

RUN apk add --no-cache musl-dev gcc git

WORKDIR /workspace/{name}
COPY . .

RUN cargo build --release

# === RUNTIME STAGE ===
FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /{name}

COPY --from=builder /workspace/{name}/target/release/{name} /{name}/{name}

ENTRYPOINT ["/{name}/{name}"]
"""
    else:
        dockerfile = f"""# === BUILD STAGE (Compile CGO libunilog.so) ===
FROM golang:1.25-alpine AS go-builder

WORKDIR /workspace

RUN apk add --no-cache git gcc musl-dev libc-dev

RUN git clone --depth 1 -b develop https://github.com/Bastien-Antigravity/microservice-toolbox.git /workspace/microservice-toolbox && \\
    git clone --depth 1 -b develop https://github.com/Bastien-Antigravity/distributed-config.git /workspace/distributed-config && \\
    git clone --depth 1 -b develop https://github.com/Bastien-Antigravity/safe-socket.git /workspace/safe-socket && \\
    git clone --depth 1 -b develop https://github.com/Bastien-Antigravity/universal-logger.git /workspace/universal-logger && \\
    git clone --depth 1 -b develop https://github.com/Bastien-Antigravity/flexible-logger.git /workspace/flexible-logger && \\
    cd /workspace/universal-logger && \\
    go build -buildmode=c-shared -o /workspace/libunilog.so ./src/cgo_bridge

# === PYTHON RUNTIME STAGE ===
FROM python:3.12-alpine

LABEL org.opencontainers.image.source="https://github.com/Bastien-Antigravity/{name}"

RUN apk add --no-cache ca-certificates tzdata git build-base

WORKDIR /{name}

# Install compiled libunilog.so system-wide
COPY --from=go-builder /workspace/libunilog.so /usr/local/lib/libunilog.so

# Clone & install microservice-toolbox python package
RUN git clone --depth 1 -b develop https://github.com/Bastien-Antigravity/microservice-toolbox.git /tmp/microservice-toolbox && \\
    pip install --no-cache-dir /tmp/microservice-toolbox/python && \\
    rm -rf /tmp/microservice-toolbox

# Install service dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy service source
COPY . .

ENTRYPOINT ["python3", "main.py"]
"""
    create_file(target_dir / "Dockerfile", dockerfile, dry_run)

    # 2. docker-compose.yml (Local fragment)
    compose_yml = f"""services:
  {name}:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/bastien-antigravity/{name}:${{TAG:-latest}}
    container_name: {name}
    restart: unless-stopped
    ports:
      - "${{HOST_IP:-127.0.0.1}}:{port}:{port}"
    volumes:
      - ./standalone.yaml:/{name}/standalone.yaml:ro
    networks:
      - teleremote-network

networks:
  teleremote-network:
    name: teleremote-network
    external: true
"""
    create_file(target_dir / "docker-compose.yml", compose_yml, dry_run)

    # 3. AGENTS.md
    test_cmd = "go test -v ./..." if lang == "go" else ("pytest" if lang == "python" else "cargo test")
    build_cmd = f"go build -o bin/{name} ./cmd/{name}" if lang == "go" else ("pip install -r requirements.txt" if lang == "python" else "cargo build")
    run_cmd = f"./bin/{name}" if lang == "go" else ("python3 main.py" if lang == "python" else "./target/debug/" + name)

    agents_md = f"""# AGENTS.md: {name}

## Service Mission & Architecture Role
`{name}` is responsible for: {desc}.

- **Exposed Capability**: `{cap_name}` (Port: `{port}`)
- **Shared Libraries**: `microservice-toolbox`, `universal-logger`, `distributed-config`, `safe-socket`
- **Configuration Link**: `standalone.yaml -> ../docker-deployment/modes/local/config/native.yaml`

## Key Build & Test Commands
```bash
# Build binary
{build_cmd}

# Run tests
{test_cmd}

# Run service locally
{run_cmd}
```

## AI Development & Integration Guidelines
1. **Bootstrap Ritual**: Initialized using `toolbox_bootstrap.BootstrapService("{name}")`. Never bypass the toolbox bootstrapper.
2. **Dynamic Port Resolution**: Always use `appConfig.GetListenAddr("{cap_name}")` or `GetCapability("{cap_name}", &cap)`. NEVER hardcode IP or port numbers.
3. **Encrypted Secrets**: Sensitive values stored in configurations must remain encrypted as `ENC(...)` tokens until runtime decryption via `appConfig.DecryptSecret()`.
4. **Header Ritual**: All source files MUST begin with the standard Triple-Block header (`ESSENTIAL PROCESS`, `DATA FLOW`, `KEY PARAMETERS`).
5. **Section Dividers**: Use appropriate dividers (`// -----------------------------------------------------------------------------`) between exported methods and major sections.
"""
    create_file(target_dir / "AGENTS.md", agents_md, dry_run)

    # 4. AI-Init.md
    init_md = f"""---
microservice: {name}
type: governance
status: active
---

# ⚡ AI Initialization: {name}

> [!IMPORTANT] MANDATORY INITIALIZATION
> Copy and paste this prompt when starting a new session in this repository:
> 
> "1. Read the ecosystem map in **[[Ecosystem-Map-MOC]]**."
> "2. Load project constraints from **[[AI-Project-DNA]]**."
> "3. Restore session state from **[[AI-Session-State]]**."
> "4. **Sentinel Audit**: Run `python3 08-Base-Scripts/main.py preflight-check` and resolve any drift."
> "5. **Squad Protocol**: You are now the **Lead Developer**. Identify and hire the required **Specialists** from `07-Core-KMS/Role-Prompts/03-Developer/Squad/`."
"""
    create_file(target_dir / "AI-Init.md", init_md, dry_run)

    # 5. AI-Project-DNA.md
    dna_md = f"""# Metadata
- Version: 0.0.1
- Classification: Level 1 Microservice

---
microservice: {name}
type: note
status: active
tags:
- '#service/{name}'
- '#type/note'
- '#state/active'
- '#zone/3-fleet'
---

# 🧬 Project DNA: {name}

## 🎯 High-Level Intent (BDD)
- **Goal**: {desc}
- **Behavioral Source of Truth**: [[02-Business-BDD/02-Behavior-Specs/{name}/FEAT-001-Initialization.md]]

## 🛠️ Role Specifics
- **Architect**: Ensure sovereign configuration resolution via microservice-toolbox and adherence to ecosystem networking.
- **QA**: Validate unit test coverage and integration scenarios in sandbox-testing.
- **Developer**: Fulfill the capability contract defined in AGENTS.md.

## 🚦 Lifecycle & Versioning
- **Primary Branch**: `develop`
- **Protected Branches**: `main`, `master`
- **Versioning Strategy**: Semantic Versioning (v0.0.1).
- **Version Source of Truth**: `VERSION.txt`.
"""
    create_file(target_dir / "AI-Project-DNA.md", dna_md, dry_run)

    # 6. AI-Session-State.md
    session_md = f"""---
microservice: {name}
type: session-state
status: active
tags:
  - '#service/{name}'
  - '#type/session-state'
  - '#state/active'
  - '#zone/3-fleet'
---

# AI Session State: {name}

Mission-ID: MISSION-SCAFFOLD-001
Status: Initialized / Ready
"""
    create_file(target_dir / "AI-Session-State.md", session_md, dry_run)

    # 7. TODO.md
    todo_md = f"""# TODO: {name}

- [ ] Implement core business logic controllers
- [ ] Connect inter-service dependencies via microservice-toolbox
- [ ] Implement end-to-end integration tests in sandbox-testing
"""
    create_file(target_dir / "TODO.md", todo_md, dry_run)

    # 8. README.md
    readme_md = f"""# {name}

{desc}

## Architecture & Integration
See [AGENTS.md](AGENTS.md) for technical specifications, capability ports, and AI development rules.
"""
    create_file(target_dir / "README.md", readme_md, dry_run)

    # 6. VERSION.txt
    create_file(target_dir / "VERSION.txt", "0.0.1\n", dry_run)

    # 7. Makefile (Dynamic Versioning Standard - Go, Rust, C++ compiled projects)
    if lang == "go":
        makefile = f"""VERSION ?= $(shell cat VERSION.txt 2>/dev/null || echo "0.0.1")

.PHONY: all build test race vet version clean run

all: build

version:
\t@echo $(VERSION)

build:
\t@echo "Building {name} (version $(VERSION))..."
\t@mkdir -p bin
\tgo build -ldflags="-s -w" -o bin/{name} ./cmd/{name}

test:
\t@echo "Running tests for {name} (version $(VERSION))..."
\tgo test -v ./...

race:
\t@echo "Running race detector (version $(VERSION))..."
\tgo test -race -v ./...

vet:
\t@echo "Running go vet..."
\tgo vet ./...

run:
\t./bin/{name}

clean:
\t@echo "Cleaning build artifacts..."
\t@rm -rf bin/ dist/ build/
"""
        create_file(target_dir / "Makefile", makefile, dry_run)
    elif lang == "rust":
        makefile = f"""VERSION ?= $(shell cat VERSION.txt 2>/dev/null || echo "0.0.1")

.PHONY: all build test version clean run

all: build

version:
\t@echo $(VERSION)

build:
\t@echo "Building {name} (version $(VERSION))..."
\tcargo build --release

test:
\t@echo "Running tests for {name} (version $(VERSION))..."
\tcargo test

run:
\tcargo run

clean:
\t@echo "Cleaning build artifacts..."
\tcargo clean
"""
        create_file(target_dir / "Makefile", makefile, dry_run)

    # 7. quick-overview/ human onboarding
    qo_dir = target_dir / "quick-overview"
    create_file(qo_dir / "Architecture-Overview.md", f"# Architecture Overview: {name}\n\nHigh-level component overview for human readers.\n", dry_run)
    create_file(qo_dir / "Features-Behavior.md", f"# Features & Behavior: {name}\n\nKey features and behavioral specifications for human readers.\n", dry_run)
    create_file(qo_dir / "Testing-Playbook.md", f"# Testing Playbook: {name}\n\nTesting procedures for human developers.\n", dry_run)
    create_file(qo_dir / "General-Misc.md", f"# General & Miscellaneous: {name}\n\nOperational guidelines and tips.\n", dry_run)
    create_file(qo_dir / ".geminiignore", "*\n", dry_run)
    create_file(qo_dir / ".mcpignore", "*\n", dry_run)
    create_file(qo_dir / ".aiignore", "*\n", dry_run)

    # 8. standalone.yaml symlink
    create_symlink(target_dir / "standalone.yaml", "../docker-deployment/modes/local/config/native.yaml", dry_run)

    # 9. .github CI/CD Workflows and Dependabot (from 05-Fleet-Operation/04-Templates)
    workspace_root = resolve_workspace_root()
    templates_dir = workspace_root / "obsidian-brain" / "05-Fleet-Operation" / "04-Templates"

    ci_template_path = templates_dir / "Microservice" / "ci.yml"
    if ci_template_path.exists():
        ci_content = ci_template_path.read_text(encoding="utf-8")
    else:
        ci_content = """# [FLEET-ARCHITECT] Continuous Integration
name: Fleet CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  fleet-ci:
    uses: Bastien-Antigravity/fleet-operation-brain/.github/workflows/master-ci.yml@develop
    secrets: inherit
"""
    create_file(target_dir / ".github" / "workflows" / "ci.yml", ci_content, dry_run)

    dep_template_path = templates_dir / "Microservice" / "dependabot.yml"
    if dep_template_path.exists():
        dep_content = dep_template_path.read_text(encoding="utf-8")
    else:
        dep_content = """version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
"""
    create_file(target_dir / ".github" / "dependabot.yml", dep_content, dry_run)

    # 10. .gitignore
    gitignore_template = templates_dir / "gitignore-global"
    if gitignore_template.exists():
        gi_content = gitignore_template.read_text(encoding="utf-8")
    else:
        gi_content = """# System Files
.DS_Store
*.log
__pycache__/
*.pyc
.venv/
target/
bin/
dist/
"""
    create_file(target_dir / ".gitignore", gi_content, dry_run)

# -----------------------------------------------------------------------------

def generate_bdd_spec(brain_dir: Path, name: str, desc: str, dry_run: bool) -> None:
    """Generates the initial BDD behavior specification note in 02-Business-BDD."""
    bdd_dir = brain_dir / "02-Business-BDD" / "02-Behavior-Specs" / name
    feat_file = bdd_dir / "FEAT-001-Initialization.md"

    content = f"""---
microservice: {name}
type: note
status: active
tags:
- '#service/{name}'
- '#type/note'
- '#state/active'
- '#zone/3-fleet'
---
# FEAT-001: Initialization & Lifecycle Management

*Back-link: [[{name}/README|⬅️ {name}]]*
---

# Feature: Service Bootstrap & Health Supervision

## 🎯 Business Intent
- **User Story**: As a platform operator, I want `{name}` to bootstrap reliably using microservice-toolbox and report health status so that the fleet orchestrator and watchdog-agent can supervise it.
- **Problem Solved**: Eliminates configuration drift, unmonitored crashes, and unhandled SIGINT/SIGTERM terminations.

## 🎬 Scenarios (Gherkin)

### Scenario 1: Clean Startup with Valid Configuration
- **Given** the ecosystem configuration file `standalone.yaml` is present
- **When** `{name}` is launched
- **Then** it must connect to required capabilities without panicking
- **And** it must log an initial startup confirmation via universal-logger
- **And** it must register cleanly with the process lifecycle manager

### Scenario 2: Graceful Termination on OS Signal
- **Given** `{name}` is running
- **When** a SIGINT or SIGTERM signal is received
- **Then** the service must execute all registered shutdown hooks
- **And** it must flush active log buffers
- **And** it must exit with status code 0

## 🛠️ Technical Constraints
- **Bootstrap**: MUST initialize via `microservice-toolbox`.
- **Secrets**: MUST decrypt any `ENC(...)` parameters on demand.
"""
    create_file(feat_file, content, dry_run)

# -----------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Fabricate a standard Bastien-Antigravity microservice skeleton.")
    parser.add_argument("--name", "-n", help="Microservice name (e.g. market-observer)")
    parser.add_argument("--lang", "-l", choices=["go", "python", "rust"], default="go", help="Language (go, python, rust)")
    parser.add_argument("--port", "-p", type=int, default=8090, help="Default capability listen port")
    parser.add_argument("--desc", "-d", default="Ecosystem microservice component", help="Short mission description")
    parser.add_argument("--dest", help="Destination path (defaults to ../<name>)")
    parser.add_argument("--dry-run", action="store_true", help="Preview file fabrication without writing to disk")

    args = parser.parse_args()

    name = args.name
    if not name:
        name = input("Enter new microservice name (e.g. market-observer): ").strip()
        if not name:
            print("❌ Error: Service name is required.")
            sys.exit(1)

    lang = args.lang
    port = args.port
    desc = args.desc
    dry_run = args.dry_run

    workspace_root = resolve_workspace_root()
    target_dir = Path(args.dest).resolve() if args.dest else workspace_root / name
    brain_dir = workspace_root / "obsidian-brain"

    print(f"\n🚀 Fabricating microservice '{name}' ({lang}) at {target_dir}...")

    if target_dir.exists() and not dry_run:
        print(f"⚠️ Warning: Target directory {target_dir} already exists. Proceeding with caution.")

    # 1. Generate language specific scaffold
    if lang == "go":
        generate_go_scaffold(target_dir, name, port, desc, dry_run)
    elif lang == "python":
        generate_python_scaffold(target_dir, name, port, desc, dry_run)
    elif lang == "rust":
        generate_rust_scaffold(target_dir, name, port, desc, dry_run)

    # 2. Generate common ecosystem files
    generate_common_files(target_dir, name, lang, port, desc, dry_run)

    # 3. Generate BDD specification stub
    generate_bdd_spec(brain_dir, name, desc, dry_run)

    cap_name = name.replace("-", "_")

    print("\n" + "=" * 80)
    print(f"🎉 Microservice '{name}' successfully scaffolded!")
    print("=" * 80)
    print("\n📋 REQUIRED FLEET REGISTRATION CHECKLIST (THE 8 TOUCHPOINTS):")
    print("1. [docker-deployment/modes/local/config/native.yaml] Add capability:")
    print(f"""       {cap_name}:
           ip: ${{HOST_IP:-127.0.0.1}}
           port: "${{{name.upper().replace('-', '_')}_PORT:-{port}}}"
""")
    print(f"2. [docker-deployment/modes/docker/config/services/{name}.yaml] Create container config slice:")
    print(f"""       capabilities:
         {cap_name}:
           ip: 0.0.0.0
           port: "{port}"
         nats_server:
           ip: nats-server
           port: 4222
         log_server:
           ip: log-server
           port: 9020
         config_server:
           ip: config-server
           port: 3306
         timescale_db:
           ip: timescale-db
           port: 5432
""")
    print("3. [docker-deployment/docker-compose.yaml] Add service container:")
    print(f"""     {name}:
       image: ghcr.io/bastien-antigravity/{name}:${{TAG:-develop}}
       build:
         context: ../{name}
         dockerfile: Dockerfile
       container_name: {name}
       restart: unless-stopped
       volumes:
         - ./modes/docker/config/services/{name}.yaml:/{name}/standalone.yaml:ro
       networks:
         teleremote-network:
           aliases:
             - {name}
""")
    print("4. [watchdog-agent/src/config/heal.go] Add symlink target:")
    print(f'       filepath.Join(rootDir, "{name}", "standalone.yaml"),\n')
    print("5. [docker-deployment/scripts/common.py] Add to SERVICES_SPEC (for fleet.sh compile/status):")
    bin_rel = f"{name}/bin/{name}" if lang == "go" else (f"{name}/target/debug/{name}" if lang == "rust" else "")
    build_c = f'["go", "build", "-o", "bin/{name}" + EXE_EXT, "./cmd/{name}"]' if lang == "go" else ('["cargo", "build"]' if lang == "rust" else "None")
    print(f"""       {{
         "name": "{name}",
         "proc_pattern": "{name}",
         "win_exe": "{name}.exe",
         "rel_dir": "{name}",
         "build_cmd": {build_c},
         "bin_path": "{bin_rel}" + EXE_EXT,
         "port": {port},
         "protocol": "REST",
       }}
""")
    print("6. [obsidian-brain/05-Fleet-Operation/00-Repo-Control/service-registry.json] Register service:")
    print(f"""       {{
         "name": "{name}",
         "image": "ghcr.io/bastien-antigravity/{name}",
         "default_port": {port},
         "protocol": "REST",
         "archetype": "Microservice",
         "classification": "level1_microservice"
       }}
""")
    print("7. [obsidian-brain/05-Fleet-Operation/00-Repo-Control/inventory.json] Register repository:")
    print(f"""       {{
         "name": "{name}",
         "path": "./{name}",
         "remote": "https://github.com/Bastien-Antigravity/{name}.git",
         "master_branch": "develop",
         "repo_type": "level1-microservice"
       }}
       (Or run: python3 obsidian-brain/08-Base-Scripts/main.py build-inventory)
""")
    print("8. [UI & Remote Integration] (Optional / If Interactive):")
    print("   - OpenMFE: Auto-registers with web-interface at http://127.0.0.1:5000/api/v1/register")
    print("   - Tele-Remote: Push dynamic UI menu over gRPC (Port 1863)")
    print("=" * 80 + "\n")

if __name__ == "__main__":
    main()
